apiVersion: v1
kind: Service
metadata:
  name: taskmaster-svc
  namespace: taskmaster-ns
spec:
  selector:
    app: flask-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30005
  type: NodePort
