apiVersion: apps/v1
kind: Deployment
metadata:
  name : taskmaster
  namespace: taskmaster-ns
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: mnmanish/taskmaster:latest
        ports:
          - containerPort: 5000
        imagePullPolicy: Always
